Setup initial version of password-store.
rbartlensky/pwvlt pull request #1
Opened 2019-10-02 12:00 UTC by rbartlensky

Currently it supports:
 * storing passwords on local keyring
 * getting passwords from local keyring and nitrokey
The `nitrokey-rs` folder will be removed as soon as the crate from `crates.io`
is updated.

2019-10-02 13:42 UTC, gabi-250 requested changes
Looks like a good start! 

A few other comments:
* perhaps list the dependencies in the README (e.g. libhidapi-dev)
* `nitro-key` -> `nitrokey`

2019-10-02 13:42 UTC, gabi-250 commented on src/config.rs
> +const TOML_NAME: &'static str = "defaults.toml";
I suggest renaming this to `DEFAULTS_TOML`.

2019-10-02 13:42 UTC, gabi-250 commented on src/config.rs
> +const DEFAULTS_PATH: &'static str = "/home/robert/.config/password-store-rust";
Don't hard-code the home directory.

2019-10-02 13:42 UTC, gabi-250 commented on src/config.rs
> +    defaults.read_to_string(&mut toml_payload)?;
Use `std::fs::read_to_string` instead.

2019-10-02 13:42 UTC, gabi-250 commented on src/config.rs
> +    let mut config_file = File::create(Path::new(DEFAULTS_PATH).join(TOML_NAME))?;
Use `std::fs::write` instead.

2019-10-02 13:42 UTC, gabi-250 commented on src/get.rs
> +use nitrokey::{connect, SLOT_COUNT};
You could group these under `nitrokey::`.

2019-10-02 13:42 UTC, gabi-250 commented on src/config.rs
> +pub fn get_config_toml() -> Result<Map<String, Value>, PasswordStoreError> {
Maybe rename this to `parse_config`.

2019-10-02 13:42 UTC, gabi-250 commented on src/get.rs
> +fn get_default_username(service: &str) -> Result<String, PasswordStoreError> {
`get_default_username` -> `default_username`

2019-10-02 13:42 UTC, gabi-250 commented on src/get.rs
> +fn xclip(payload: &str) -> Result<(), PasswordStoreError> {
It's probably a better idea to use [clipboard](https://crates.io/crates/clipboard).

2019-10-02 13:42 UTC, gabi-250 commented on src/get.rs
> +        _ => {
Should this function return a `Result` instead?

2019-10-02 13:42 UTC, gabi-250 commented on src/get.rs
> +    let password_safe = device.get_password_safe(&pin).unwrap();
We probably need an error type for nitrokey-related errors (e.g. wrong pin).

2019-10-02 13:42 UTC, gabi-250 commented on src/get.rs
> +        None => {
It might be worth printing a message to indicate where the password was retrieved from.

2019-10-02 13:42 UTC, gabi-250 commented on src/main.rs
> +    let matches = App::new("Password store")
`Password store` sounds a little generic :-).

2019-10-02 13:42 UTC, gabi-250 commented on src/main.rs
> +            Arg::with_name("get")
I think this should be `service`, not `get`.

2019-10-02 13:42 UTC, gabi-250 commented on src/main.rs
> +            Arg::with_name("set")
`set` -> `service`

2019-10-02 13:42 UTC, gabi-250 commented on src/set.rs
> +    let pass = Command::new("pwgen")
Consider using an external crate to generate passwords. [passwords](https://crates.io/crates/passwords) is fairly similar to `pwgen`.

2019-10-02 13:42 UTC, gabi-250 commented on src/set.rs
> +    if let None = toml.get(service) {
I prefer `toml.get(service).is_none()`, but it's entirely up to you.

2019-10-03 13:05 UTC, rbartlensky commented
@gabi-250 Thank you for your comments. I think the last commit should address everything you mentioned!

2019-10-03 15:27 UTC, gabi-250 approved these changes
Looks good to me. Do you want to squash?

2019-10-03 15:29 UTC, rbartlensky commented
Squashed!

2019-10-03 15:33 UTC, merged